#!/bin/bash
APP_NAME="Zed"
APP_COMMENT="Code Editor with AI agents"
INSTALL_TYPE="tarball"
PACKAGE_NAME="zed"
DOWNLOAD_URL="https://cloud.zed.dev/releases/stable/latest/download?asset=zed&arch=x86_64&os=linux"
ICON_URL="https://github.com/zed-industries/zed/raw/refs/heads/main/crates/zed/resources/app-icon.png"
ICON_NAME="zed.png"
DESKTOP_FILE="dev.zed.Zed.desktop"
CATEGORIES="Development;IDE;TextEditor;"
EXEC_NAME="zed"
EXEC_SUBPATH="bin/zed"
INSTALL_DIR="$HOME/.local/lib/zed"
BIN_DIR="$HOME/.local/bin"
